In [1]:
import pandas as pd
import numpy as np
import gc; gc.enable()
import lightgbm as lgb
import warnings 
warnings.filterwarnings('ignore')

from GridSearcher import data_loader, model_loader, fit_params, get_oof_predictions
from tqdm import tqdm

In [2]:
DATA_TYPE = 'sparse'
DATA_NORMALIZE = True
IS_REGRESSION = True
SEED = 519

In [3]:
dl = data_loader(data_type=DATA_TYPE, is_regression=IS_REGRESSION, is_train=True, is_pure=True)
train_X, train_y = dl.load()

Arguments: sparse True True
target loaded


In [4]:
dl_test = data_loader(data_type=DATA_TYPE, is_regression=IS_REGRESSION, is_train=False, is_pure=True)
test_X = dl_test.load()

Arguments: sparse True False
target loaded


In [5]:
train_X.shape, train_y.shape, test_X.shape

((1503424, 38406), (1503424,), (508438, 38406))

In [6]:
train_y

array([ 0.    ,  0.    ,  0.    , ...,  0.7376,  0.    ,  0.7376])

## Ridge

In [7]:
ml = model_loader(model_type='rg')

In [8]:
fit_param = None

In [8]:
default_params = {
    'alpha':1.0, 
    'fit_intercept':True, 
    'normalize':False, 
    'copy_X':True, 
    'max_iter':None, 
    'tol':0.001, 
    'solver':'auto', 
    'random_state': SEED
}

try_params = {
    'alpha': [1., 2., 4., 8., 16.]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=True)

{'alpha': 1.0} train loss: 0.218961, valid loss:0.226523, loss_diff:0.007563
{'alpha': 1.0} train loss: 0.219196, valid loss:0.225495, loss_diff:0.006298
{'alpha': 1.0} train loss: 0.218992, valid loss:0.226428, loss_diff:0.007435
{'alpha': 1.0} train loss: 0.219083, valid loss:0.226062, loss_diff:0.006978
{'alpha': 1.0} train loss: 0.219072, valid loss:0.225943, loss_diff:0.006871
=================>{'alpha': 1.0} loss:0.226090
{'alpha': 2.0} train loss: 0.219400, valid loss:0.226693, loss_diff:0.007294
{'alpha': 2.0} train loss: 0.219648, valid loss:0.225647, loss_diff:0.005999
{'alpha': 2.0} train loss: 0.219435, valid loss:0.226599, loss_diff:0.007165
{'alpha': 2.0} train loss: 0.219528, valid loss:0.226240, loss_diff:0.006712
{'alpha': 2.0} train loss: 0.219519, valid loss:0.226102, loss_diff:0.006583
=================>{'alpha': 2.0} loss:0.226256
{'alpha': 4.0} train loss: 0.219909, valid loss:0.226788, loss_diff:0.006879
{'alpha': 4.0} train loss: 0.220164, valid loss:0.225728, l

param  val_loss_mean  val_loss_std
0   {'alpha': 1.0}       0.226090      0.000368
1   {'alpha': 2.0}       0.226256      0.000375
2   {'alpha': 4.0}       0.226345      0.000381
3   {'alpha': 8.0}       0.226306      0.000386
4  {'alpha': 16.0}       0.226195      0.000390

In [9]:
default_params = {
    'alpha':1.0, 
    'fit_intercept':True, 
    'normalize':False, 
    'copy_X':True, 
    'max_iter':None, 
    'tol':0.001, 
    'solver':'auto', 
    'random_state': SEED
}

try_params = {
    'alpha': [0.01, 0.05, 0.1, 0.5,]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=True)

{'alpha': 0.01} train loss: 0.218195, valid loss:0.226164, loss_diff:0.007969
{'alpha': 0.01} train loss: 0.218413, valid loss:0.225180, loss_diff:0.006768
{'alpha': 0.01} train loss: 0.218227, valid loss:0.226079, loss_diff:0.007852
{'alpha': 0.01} train loss: 0.218282, valid loss:0.225684, loss_diff:0.007402
{'alpha': 0.01} train loss: 0.218264, valid loss:0.225537, loss_diff:0.007273
=================>{'alpha': 0.01} loss:0.225729
{'alpha': 0.05} train loss: 0.218237, valid loss:0.226182, loss_diff:0.007945
{'alpha': 0.05} train loss: 0.218456, valid loss:0.225195, loss_diff:0.006739
{'alpha': 0.05} train loss: 0.218269, valid loss:0.226097, loss_diff:0.007828
{'alpha': 0.05} train loss: 0.218327, valid loss:0.225702, loss_diff:0.007376
{'alpha': 0.05} train loss: 0.218313, valid loss:0.225562, loss_diff:0.007249
=================>{'alpha': 0.05} loss:0.225748
{'alpha': 0.1} train loss: 0.218289, valid loss:0.226206, loss_diff:0.007917
{'alpha': 0.1} train loss: 0.218508, valid loss

param  val_loss_mean  val_loss_std
0  {'alpha': 0.01}       0.225729      0.000361
1  {'alpha': 0.05}       0.225748      0.000361
2   {'alpha': 0.1}       0.225770      0.000362
3   {'alpha': 0.5}       0.225942      0.000363

In [10]:
default_params = {
    'alpha':1.0, 
    'fit_intercept':True, 
    'normalize':False, 
    'copy_X':True, 
    'max_iter':None, 
    'tol':0.001, 
    'solver':'auto', 
    'random_state': SEED
}

try_params = {
    'alpha': [32, 64, 128]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=True)

{'alpha': 32} train loss: 0.222047, valid loss:0.226603, loss_diff:0.004556
{'alpha': 32} train loss: 0.222307, valid loss:0.225534, loss_diff:0.003228
{'alpha': 32} train loss: 0.222079, valid loss:0.226539, loss_diff:0.004460
{'alpha': 32} train loss: 0.222180, valid loss:0.226074, loss_diff:0.003895
{'alpha': 32} train loss: 0.222193, valid loss:0.225945, loss_diff:0.003752
=================>{'alpha': 32} loss:0.226139
{'alpha': 64} train loss: 0.223124, valid loss:0.226740, loss_diff:0.003616
{'alpha': 64} train loss: 0.223384, valid loss:0.225672, loss_diff:0.002288
{'alpha': 64} train loss: 0.223151, valid loss:0.226692, loss_diff:0.003541
{'alpha': 64} train loss: 0.223262, valid loss:0.226186, loss_diff:0.002924
{'alpha': 64} train loss: 0.223283, valid loss:0.226079, loss_diff:0.002796
=================>{'alpha': 64} loss:0.226274
{'alpha': 128} train loss: 0.224362, valid loss:0.227131, loss_diff:0.002769
{'alpha': 128} train loss: 0.224618, valid loss:0.226051, loss_diff:0.0

param  val_loss_mean  val_loss_std
0   {'alpha': 32}       0.226139      0.000396
1   {'alpha': 64}       0.226274      0.000400
2  {'alpha': 128}       0.226659      0.000407

In [9]:
for alpha in [0.001, 1., 16., 32.]:
    name = 'alpha_'+str(alpha).replace(".","")
    default_params = {
        'alpha':alpha, 
        'fit_intercept':True, 
        'normalize':False, 
        'copy_X':True, 
        'max_iter':None, 
        'tol':0.001, 
        'solver':'auto', 
        'random_state': SEED
    }
    ret, ret_test, _ = get_oof_predictions(train_X, train_y, test_X, ml, default_params, seed=SEED, fit_params=None, use_eval_set=False, predict_proba=False)
    pd.DataFrame(data=ret, columns=[name+'_pred']).to_csv(name+'_oof_val_pred.csv', index=False)
    pd.DataFrame(data=ret_test, columns=[name+'_pred']).to_csv(name+'_oof_test_pred.csv', index=False)

Fold 1 completed.
Fold 2 completed.
Fold 3 completed.
Fold 4 completed.
Fold 5 completed.
Fold 1 completed.
Fold 2 completed.
Fold 3 completed.
Fold 4 completed.
Fold 5 completed.
Fold 1 completed.
Fold 2 completed.
Fold 3 completed.
Fold 4 completed.
Fold 5 completed.
Fold 1 completed.
Fold 2 completed.
Fold 3 completed.
Fold 4 completed.
Fold 5 completed.


## KNN

In [2]:
ml = model_loader(model_type='knn')

NameError: name 'model_loader' is not defined

In [ ]:
# try best neighbors

In [ ]:
# get n=5, 10, 100, 500 features

In [ ]:
'''
non-cat: 57: 10/11 ==> first=38349 (38409-38349)=57 => 38358\38359
cat: 9 
'''

In [10]:
from sklearn.model_selection import KFold
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import vstack

In [9]:
reduced_X = TruncatedSVD(n_components=300).fit_transform(vstack([train_X, test_X]).tocsr())

import pickle
with open('reduced_sparse_features.pickle', 'wb') as handle:
    pickle.dump(reduced_X, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [7]:
import pickle
from sklearn.model_selection import KFold
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import vstack
with open('reduced_sparse_features.pickle', 'rb') as handle:
    reduced_X = pickle.load(handle)

reduced_X.shape

(2011862, 300)

In [8]:
class knn_feature_wrapper():
    def __init__(self, params, seed=519):
        self.params = params
        self.seed = seed
        
    def transform(self, X, y, test_X, reduced_X,
                  n_list=[5, 10, 100, 500],
                  feature_inds=[38358, 38359],
                  feature_cols=['price', 'item_seq_number']):
        def get_model():
            return model_loader(model_type='knn').load(self.params)
        
        def get_feature_names(n):
            return ['{}_{}_closest_mean'.format(feat, n) for feat in feature_cols]
        
        train_res = pd.DataFrame()
        test_res = pd.DataFrame()
        for n in n_list:
            train_res['{}_closest_avg_dist'.format(n)] = np.zeros((X.shape[0],))
            test_res['{}_closest_avg_dist'.format(n)] = np.zeros((test_X.shape[0],))
            train_res['{}_closest_avg_target'.format(n)]  = np.zeros((X.shape[0],))
            test_res['{}_closest_avg_target'.format(n)]  = np.zeros((test_X.shape[0],))
            for feat in feature_cols:
                train_res['{}_{}_closest_mean'.format(feat, n)] = np.zeros((X.shape[0],))
                test_res['{}_{}_closest_mean'.format(feat, n)] = np.zeros((test_X.shape[0],))
        
        for train_ix, val_ix in KFold(5, shuffle=True, random_state=self.seed).split(X):
            md = get_model()
            
            tr_X, tr_y = X[train_ix,:], y[train_ix]
            
            md.fit(reduced_X[train_ix, :], tr_y)
            all_val_dist, all_val_ind = md.kneighbors(reduced_X[val_ix,:], max(n_list), return_distance=True)
            print('Getting validation n-neighbors done.')
            all_test_dist, all_test_ind = md.kneighbors(reduced_X[X.shape[0]:,:], max(n_list), return_distance=True)
            print('Getting test n-neighbors done.')
            
            for n in n_list:
                val_dist, val_ind = all_val_dist[:, :n], all_val_ind[:, :n]
                test_dist, test_ind = all_test_dist[:, :n], all_test_ind[:, :n]
                
                train_res.loc[val_ix, '{}_closest_avg_dist'.format(n)] = val_dist.mean(axis=1)
                train_res.loc[val_ix, get_feature_names(n)] = \
                    np.array([tr_X[ind,:][:,feature_inds].mean(axis=0) for ind in tqdm(val_ind)])
                train_res.loc[val_ix, '{}_closest_avg_target'.format(n)] = \
                    np.array([tr_y[ind].mean() for ind in tqdm(val_ind)])
                
                test_res.loc[:, '{}_closest_avg_dist'.format(n)] += test_dist.mean(axis=1)
                test_res.loc[:, get_feature_names(n)] += \
                    np.array([tr_X[ind,:][:,feature_inds].mean(axis=0) for ind in tqdm(test_ind)])
                test_res.loc[:, '{}_closest_avg_target'.format(n)] += \
                    np.array([tr_y[ind].mean() for ind in tqdm(test_ind)])
                
                print(n, ' finished')
                
            del md, all_val_dist, all_val_ind
            
        test_res.loc[:, :] /= 5
        return train_res, test_res

In [8]:
# testing code
params = {
    'p': 2,
    'n_jobs': 1,
    
}
kfw = knn_feature_wrapper(params)
temp_X, temp_y, temp_test_X = np.zeros((5, 3)), np.zeros((5,)), np.zeros((4, 3))
temp_X[:, 0] = 0
temp_X[:, 1] = 1
temp_X[:, 2] = 2
temp_y[1] = 1
temp_test_X[:1, 0] = 1
temp_test_X[:2, 1] = 1
temp_test_X[:3, 2] = 1

print(temp_X)
print(temp_y)
print(temp_test_X)

kfw.transform(temp_X, temp_y, temp_test_X, 
              n_list=[2, 3],
              feature_inds=[1, 2],
              feature_cols=['price', 'item_seq_number'])

[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]]
[ 0.  1.  0.  0.  0.]
[[ 1.  1.  1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
Getting n neighbors done.


100%|██████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4000.29it/s]


2  finished


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


3  finished
Getting n neighbors done.


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


2  finished


100%|██████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4000.29it/s]


3  finished
Getting n neighbors done.


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


2  finished


100%|██████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4000.29it/s]


3  finished
Getting n neighbors done.


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


2  finished


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


3  finished
Getting n neighbors done.


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


2  finished


100%|████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


3  finished


(   2_closest_avg_dist  2_closest_avg_target  price_2_closest_mean  \
 0                 0.0                   0.5                   1.0   
 1                 0.0                   0.0                   1.0   
 2                 0.0                   0.5                   1.0   
 3                 0.0                   0.5                   1.0   
 4                 0.0                   0.5                   1.0   
 
    item_seq_number_2_closest_mean  3_closest_avg_dist  3_closest_avg_target  \
 0                             2.0                 0.0              0.333333   
 1                             2.0                 0.0              0.000000   
 2                             2.0                 0.0              0.333333   
 3                             2.0                 0.0              0.333333   
 4                             2.0                 0.0              0.333333   
 
    price_3_closest_mean  item_seq_number_3_closest_mean  
 0                   1.0             

In [ ]:
params = {
    'p': 2,
    'n_jobs': 3,   
}
kfw = knn_feature_wrapper(params)
train_res, test_res = kfw.transform(train_X, train_y, test_X, reduced_X, n_list=[2, 5, 10, 30])

In [ ]:
train_res.head(3)

In [ ]:
test_res.head(3)

In [ ]:
train_res.to_csv('train_knn_features.csv', index=False)
test_res.to_csv('test_knn_features.csv', index=False)

## MLP (Need tensorflow + keras)

In [1]:
import pandas as pd
import tensorflow as tf
from keras.preprocessing import text, sequence
import numpy as np
from keras.layers import Input, SpatialDropout1D,Dropout, GlobalAveragePooling1D, GRU, Bidirectional, LSTM, Dense, Embedding, concatenate, Embedding, Flatten, Activation, BatchNormalization, regularizers
from keras.initializers import Orthogonal
from keras.models import Model, Sequential
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, LambdaCallback, Callback, LearningRateScheduler
import keras.backend as K
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
import os
import pickle
import gc; gc.enable()

ModuleNotFoundError: No module named 'keras'

In [3]:
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
K.tensorflow_backend._get_available_gpus()

[name: "/cpu:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1596168217501253868
]


NameError: name 'K' is not defined

In [8]:
def root_mean_squared_error(y_true, y_pred):
    return K.sqrt(K.mean(K.square(K.clip(y_pred, 0., 1.) - y_true), axis=-1))

def build_model(X):
    # define the architecture of the network
    main_in = Input(shape=[X.shape[1]])
    main = Dropout(0.1)(main_in)
    main = Dense(512, activation='relu')(main)
    main = Dense(128, activation='relu')(main)
    out = Dense(1, activation = "linear")(main)
    model = Model(main_in, out)
    
    '''
    model = Sequential()
    model.add(Input(shape=(32,)))
    model.add(Dropout(0.1))
    model.add(Dense(512, input_dim=X.shape[1], kernel_initializer="glorot_normal", activation="relu"))
    model.add(Dense(256, kernel_initializer="glorot_normal", activation="relu"))
    model.add(Dense(1, activation = "linear"))
    '''
    model.compile(optimizer = Adam(lr=0.0005), loss = 'mean_squared_error',
                  metrics =[root_mean_squared_error])
    model.summary()
    return model

In [9]:
def clip_rmse(true, prediction):
    return np.sqrt(metrics.mean_squared_error(true, np.clip(prediction, 0., 1.)))
    
class NBatchEvalLogger(Callback):
    def __init__(self, display, val_X, val_y, save_path=None, save_start=1000):
        self.step = 0
        self.display = display
        self.val_X = val_X
        self.val_y = val_y
        self.best_loss = None
        self.save_path = save_path
        self.save_start = save_start
        self.record_count = 0
        
    def on_batch_end(self, batch, logs={}):
        self.step += 1
        if self.step % self.display == 0 and self.step >= self.save_start:
            #loss, metric = self.model.evaluate(self.val_X, self.val_y, batch_size=128, verbose=1)
            prediction = self.model.predict(self.val_X, batch_size=128, verbose=0)
            loss = clip_rmse(self.val_y, prediction)
            
            if self.best_loss is None:
                self.best_loss = loss
            else:
                if loss < self.best_loss:
                    self.best_loss = loss
                    if self.save_path is not None:
                        self.model.save(self.save_path, overwrite=True)
                        self.record_count += 1
                    
            print('\nstep: {} val loss={:.5f}, best loss={:.5f}'.format(self.step, loss, self.best_loss))

In [10]:
from sklearn.model_selection import KFold
kf = KFold(5, shuffle=True, random_state=SEED)

ret = np.zeros((train_X.shape[0],))
ret_test = np.zeros((test_X.shape[0],))
ret_models = []

EPOCHS = 4
fold=1
for train_ix, val_ix in kf.split(train_X):
    
    model = build_model(train_X)
    file_path = "mlp_model_{}.hdf5".format(fold)
    #check_point = ModelCheckpoint(file_path, monitor = "val_loss", mode = "min", save_best_only = True, verbose = 1)
    check_point = NBatchEvalLogger(2000, train_X[val_ix,:], train_y[val_ix], save_path=file_path, save_start=2000)
    lr_schd = LearningRateScheduler(lambda epoch: 0.0005*(0.2**(epoch//2)), verbose=1)
    
    history = model.fit(train_X[train_ix,:], train_y[train_ix], batch_size = 128, epochs = EPOCHS, 
                        validation_data = (train_X[val_ix,:], train_y[val_ix]),
                        verbose = 1, callbacks = [lr_schd, check_point])

    model.load_weights(file_path)
    ret[val_ix] = model.predict(train_X[val_ix,:])
    ret_test += model.predict(test_X).reshape((test_X.shape[0],))
    ret_models.append(model)
    
    del model; gc.collect()
    fold += 1

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 38406)             0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 38406)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               19664384  
_________________________________________________________________
dense_2 (Dense)              (None, 128)               65664     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129       
Total params: 19,730,177
Trainable params: 19,730,177
Non-trainable params: 0
_________________________________________________________________
Train on 1202739 samples, validate on 300685 samples
Epoch 1/4

Epoch 00001: LearningRateScheduler reducing learning rate to 0.000

1024000/1202739 [========================>.....] - ETA: 2:50 - loss: 0.0523 - root_mean_squared_error: 0.1521
step: 8000 val loss=0.22457, best loss=0.22457
1202739/1202739 [==============================] - 1295s 1ms/step - loss: 0.0521 - root_mean_squared_error: 0.1517 - val_loss: 0.0507 - val_root_mean_squared_error: 0.1477
Epoch 2/4

Epoch 00002: LearningRateScheduler reducing learning rate to 0.0005.
  77184/1202739 [>.............................] - ETA: 12:17 - loss: 0.0486 - root_mean_squared_error: 0.1445
step: 10000 val loss=0.22571, best loss=0.22457
 333184/1202739 [=======>......................] - ETA: 13:50 - loss: 0.0489 - root_mean_squared_error: 0.1449
step: 12000 val loss=0.22427, best loss=0.22427
 589184/1202739 [=============>................] - ETA: 10:11 - loss: 0.0489 - root_mean_squared_error: 0.1449
step: 14000 val loss=0.22392, best loss=0.22392
 845184/1202739 [====================>.........] - ETA: 6:02 - loss: 0.0490 - root_mean_squared_error: 0.1451
step

In [13]:
ret_test /= 5

In [16]:
ret_test

array([ 0.324957  ,  0.1405607 ,  0.21151634, ...,  0.03753489,
        0.44956121,  0.0730801 ])

In [14]:
pd.DataFrame(data=ret, columns=['mlp_pred']).to_csv('mlp_oof_val_pred.csv', index=False)
pd.DataFrame(data=ret_test, columns=['mlp_pred']).to_csv('mlp_oof_test_pred.csv', index=False)

In [15]:
test_df = pd.read_csv("test.csv", usecols=['item_id'])
test_pred = pd.read_csv("mlp_oof_test_pred.csv")
test_pred = test_pred.loc[:, 'mlp_pred'].values
pd.DataFrame(np.clip(test_pred,0,1), 
             index=test_df.item_id,
             columns=['deal_probability']).to_csv('mlp_submission.csv')

## Logistic Regression

In [7]:
ml = model_loader(model_type='lr')
fit_param=None
from sklearn.metrics import log_loss

In [8]:
default_params = {
    'penalty': 'l2', 
    'fit_intercept':True,
    'C': 1.0
}

try_params = [
    {
        'penalty': ['l2'],
        'C': [1.0, 2., 4., 8.]
    }
]

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, 
           seed=SEED, use_eval_set=False, loss_func=log_loss, predict_proba=True)

{'C': 1.0, 'penalty': 'l2'} train loss: 0.267944, valid loss:0.290776, loss_diff:0.022831
{'C': 1.0, 'penalty': 'l2'} train loss: 0.268541, valid loss:0.287768, loss_diff:0.019226
{'C': 1.0, 'penalty': 'l2'} train loss: 0.267758, valid loss:0.291122, loss_diff:0.023364
{'C': 1.0, 'penalty': 'l2'} train loss: 0.268069, valid loss:0.289864, loss_diff:0.021795
{'C': 1.0, 'penalty': 'l2'} train loss: 0.268056, valid loss:0.289615, loss_diff:0.021559
=================>{'C': 1.0, 'penalty': 'l2'} loss:0.289829
{'C': 2.0, 'penalty': 'l2'} train loss: 0.265380, valid loss:0.291909, loss_diff:0.026529
{'C': 2.0, 'penalty': 'l2'} train loss: 0.266135, valid loss:0.288892, loss_diff:0.022757
{'C': 2.0, 'penalty': 'l2'} train loss: 0.265244, valid loss:0.292323, loss_diff:0.027080
{'C': 2.0, 'penalty': 'l2'} train loss: 0.265557, valid loss:0.290956, loss_diff:0.025399
{'C': 2.0, 'penalty': 'l2'} train loss: 0.265533, valid loss:0.290749, loss_diff:0.025216
=================>{'C': 2.0, 'penalty': 

param  val_loss_mean  val_loss_std
0  {'C': 1.0, 'penalty': 'l2'}       0.289829      0.001172
1  {'C': 2.0, 'penalty': 'l2'}       0.290966      0.001190
2  {'C': 4.0, 'penalty': 'l2'}       0.291779      0.001297
3  {'C': 8.0, 'penalty': 'l2'}       0.292425      0.001311

In [ ]:
default_params = {
    'penalty': 'l2', 
    'fit_intercept':True,
    'C': 1.0
}

try_params = [
    {
        'penalty': ['l2'],
        'C': [0.01, 0.1, 0.5]
    }
]

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, 
           seed=SEED, use_eval_set=False, loss_func=log_loss, predict_proba=True)

{'C': 0.01, 'penalty': 'l2'} train loss: 0.290417, valid loss:0.293783, loss_diff:0.003366
{'C': 0.01, 'penalty': 'l2'} train loss: 0.291078, valid loss:0.290997, loss_diff:-0.000082
{'C': 0.01, 'penalty': 'l2'} train loss: 0.290301, valid loss:0.294176, loss_diff:0.003874
{'C': 0.01, 'penalty': 'l2'} train loss: 0.290592, valid loss:0.293102, loss_diff:0.002510
{'C': 0.01, 'penalty': 'l2'} train loss: 0.290668, valid loss:0.292711, loss_diff:0.002043
=================>{'C': 0.01, 'penalty': 'l2'} loss:0.292954
{'C': 0.1, 'penalty': 'l2'} train loss: 0.278400, valid loss:0.288481, loss_diff:0.010081
{'C': 0.1, 'penalty': 'l2'} train loss: 0.279020, valid loss:0.285823, loss_diff:0.006803
{'C': 0.1, 'penalty': 'l2'} train loss: 0.278274, valid loss:0.288989, loss_diff:0.010715
{'C': 0.1, 'penalty': 'l2'} train loss: 0.278563, valid loss:0.287816, loss_diff:0.009253
{'C': 0.1, 'penalty': 'l2'} train loss: 0.278584, valid loss:0.287514, loss_diff:0.008929
=================>{'C': 0.1, 'pen

param  val_loss_mean  val_loss_std
0  {'C': 0.01, 'penalty': 'l2'}       0.292954      0.001104
1   {'C': 0.1, 'penalty': 'l2'}       0.287724      0.001081
2   {'C': 0.5, 'penalty': 'l2'}       0.288656      0.001135

In [ ]:
default_params = {
    'penalty': 'l2', 
    'fit_intercept':True,
    'C': 1.0
}

try_params = [
    {
        'penalty': ['l1'],
        'C': [1.0, 2., 4., 8.]
    }
]

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, 
           seed=SEED, use_eval_set=False, loss_func=log_loss, predict_proba=True)

## LGBM (Use Dense features)

In [6]:
ml = model_loader(model_type='lgb')

In [7]:
import pickle
with open('cat_feature_names', 'rb') as handle:
    cat_cols = pickle.load(handle)

with open('feature_names', 'rb') as handle:
    features = pickle.load(handle)

In [8]:
cat_cols

['image_top_1',
 'param_1',
 'param_2',
 'param_3',
 'city',
 'region',
 'category_name',
 'parent_category_name',
 'user_type']

In [10]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':5, 
    'learning_rate':0.3, 
    'n_estimators':2000, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

fit_param = {
    'feature_name': list(features), 
    'categorical_feature': cat_cols,
    'early_stopping_rounds': 50,
    'verbose': 100,
    'eval_metric': 'rmse'
}

try_params = {
    'random_state': [719]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=True)

Training until validation scores don't improve for 50 rounds.
[100]	train's rmse: 0.218926	valid's rmse: 0.222944


KeyboardInterrupt: 

In [9]:
fit_param = {
    'feature_name': list(features), 
    'categorical_feature': cat_cols,
}
'''
fit_param.update({
    'early_stopping_rounds': 30,
    'verbose': 100,
    'eval_metric': 'rmse'
})
'''

"\nfit_param.update({\n    'early_stopping_rounds': 30,\n    'verbose': 100,\n    'eval_metric': 'rmse'\n})\n"

In [10]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':5, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}


try_params = {
    'max_depth': [5, 6, 8]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=False)

{'max_depth': 5} train loss: 0.218505, valid loss:0.223704, loss_diff:0.005199
{'max_depth': 5} train loss: 0.219042, valid loss:0.222470, loss_diff:0.003428
{'max_depth': 5} train loss: 0.218784, valid loss:0.223454, loss_diff:0.004670
{'max_depth': 5} train loss: 0.219033, valid loss:0.222853, loss_diff:0.003820
{'max_depth': 5} train loss: 0.219184, valid loss:0.223251, loss_diff:0.004068
=================>{'max_depth': 5} loss:0.223146
{'max_depth': 6} train loss: 0.217569, valid loss:0.223429, loss_diff:0.005860
{'max_depth': 6} train loss: 0.217589, valid loss:0.221967, loss_diff:0.004378
{'max_depth': 6} train loss: 0.217316, valid loss:0.223030, loss_diff:0.005715
{'max_depth': 6} train loss: 0.217332, valid loss:0.222378, loss_diff:0.005047
{'max_depth': 6} train loss: 0.217610, valid loss:0.222590, loss_diff:0.004980
=================>{'max_depth': 6} loss:0.222679
{'max_depth': 8} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'max_depth': 8} train loss: 0.21

param  val_loss_mean  val_loss_std
0  {'max_depth': 5}       0.223146      0.000438
1  {'max_depth': 6}       0.222679      0.000508
2  {'max_depth': 8}       0.222005      0.000468

In [11]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'min_split_gain': [i/10.0 for i in range(0,5)]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED, use_eval_set=False)

{'min_split_gain': 0.0} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'min_split_gain': 0.0} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'min_split_gain': 0.0} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'min_split_gain': 0.0} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'min_split_gain': 0.0} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'min_split_gain': 0.0} loss:0.222005
{'min_split_gain': 0.1} train loss: 0.215889, valid loss:0.222735, loss_diff:0.006846
{'min_split_gain': 0.1} train loss: 0.216071, valid loss:0.221491, loss_diff:0.005419
{'min_split_gain': 0.1} train loss: 0.216219, valid loss:0.222521, loss_diff:0.006302
{'min_split_gain': 0.1} train loss: 0.216482, valid loss:0.221848, loss_diff:0.005367
{'min_split_gain': 0.1} train loss: 0.216082, valid loss:0.222172, loss_diff:0.006090
=================>{'min_split_gain': 0.1} loss:0.222154
{'min_split_gain': 0.2} trai

param  val_loss_mean  val_loss_std
0  {'min_split_gain': 0.0}       0.222005      0.000468
1  {'min_split_gain': 0.1}       0.222154      0.000449
2  {'min_split_gain': 0.2}       0.222118      0.000438
3  {'min_split_gain': 0.3}       0.222128      0.000453
4  {'min_split_gain': 0.4}       0.222124      0.000512

In [12]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'colsample_bytree':[i/10.0 for i in range(6,11)]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'colsample_bytree': 0.6} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'colsample_bytree': 0.6} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'colsample_bytree': 0.6} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'colsample_bytree': 0.6} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'colsample_bytree': 0.6} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'colsample_bytree': 0.6} loss:0.222005
{'colsample_bytree': 0.7} train loss: 0.215871, valid loss:0.222641, loss_diff:0.006770
{'colsample_bytree': 0.7} train loss: 0.216165, valid loss:0.221512, loss_diff:0.005347
{'colsample_bytree': 0.7} train loss: 0.215783, valid loss:0.222465, loss_diff:0.006682
{'colsample_bytree': 0.7} train loss: 0.216138, valid loss:0.221625, loss_diff:0.005487
{'colsample_bytree': 0.7} train loss: 0.216353, valid loss:0.222102, loss_diff:0.005748
=================>{'colsample_bytree': 0.7} loss:0.222069
{'co

param  val_loss_mean  val_loss_std
0  {'colsample_bytree': 0.6}       0.222005      0.000468
1  {'colsample_bytree': 0.7}       0.222069      0.000446
2  {'colsample_bytree': 0.8}       0.222066      0.000448
3  {'colsample_bytree': 0.9}       0.222074      0.000531
4  {'colsample_bytree': 1.0}       0.222178      0.000576

In [13]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}


try_params = {
    'colsample_bytree':[.55, .6, .65]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'colsample_bytree': 0.55} train loss: 0.216380, valid loss:0.222791, loss_diff:0.006411
{'colsample_bytree': 0.55} train loss: 0.216794, valid loss:0.221431, loss_diff:0.004637
{'colsample_bytree': 0.55} train loss: 0.216700, valid loss:0.222528, loss_diff:0.005827
{'colsample_bytree': 0.55} train loss: 0.216361, valid loss:0.221781, loss_diff:0.005420
{'colsample_bytree': 0.55} train loss: 0.216375, valid loss:0.222048, loss_diff:0.005672
=================>{'colsample_bytree': 0.55} loss:0.222116
{'colsample_bytree': 0.6} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'colsample_bytree': 0.6} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'colsample_bytree': 0.6} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'colsample_bytree': 0.6} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'colsample_bytree': 0.6} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'colsample_bytree': 0.6} loss:0.22200

param  val_loss_mean  val_loss_std
0  {'colsample_bytree': 0.55}       0.222116      0.000492
1   {'colsample_bytree': 0.6}       0.222005      0.000468
2  {'colsample_bytree': 0.65}       0.222049      0.000466

In [14]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'subsample': np.arange(.6, 1.05, .05)
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'subsample': 0.59999999999999998} train loss: 0.218250, valid loss:0.223976, loss_diff:0.005726
{'subsample': 0.59999999999999998} train loss: 0.218481, valid loss:0.222729, loss_diff:0.004248
{'subsample': 0.59999999999999998} train loss: 0.218495, valid loss:0.223856, loss_diff:0.005361
{'subsample': 0.59999999999999998} train loss: 0.218637, valid loss:0.223302, loss_diff:0.004666
{'subsample': 0.59999999999999998} train loss: 0.218761, valid loss:0.223491, loss_diff:0.004730
=================>{'subsample': 0.59999999999999998} loss:0.223471
{'subsample': 0.65000000000000002} train loss: 0.217739, valid loss:0.223566, loss_diff:0.005827
{'subsample': 0.65000000000000002} train loss: 0.217995, valid loss:0.222441, loss_diff:0.004445
{'subsample': 0.65000000000000002} train loss: 0.218073, valid loss:0.223443, loss_diff:0.005371
{'subsample': 0.65000000000000002} train loss: 0.218392, valid loss:0.222925, loss_diff:0.004533
{'subsample': 0.65000000000000002} train loss: 0.217732, val

param  val_loss_mean  val_loss_std
0  {'subsample': 0.59999999999999998}       0.223471      0.000443
1  {'subsample': 0.65000000000000002}       0.223089      0.000400
2  {'subsample': 0.70000000000000007}       0.222947      0.000449
3  {'subsample': 0.75000000000000011}       0.222819      0.000408
4  {'subsample': 0.80000000000000016}       0.222547      0.000435
5   {'subsample': 0.8500000000000002}       0.222428      0.000443
6  {'subsample': 0.90000000000000024}       0.222359      0.000412
7  {'subsample': 0.95000000000000029}       0.222186      0.000409
8   {'subsample': 1.0000000000000004}       0.222005      0.000468

In [15]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'reg_alpha':[i/10.0 for i in range(0,11,1)]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'reg_alpha': 0.0} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'reg_alpha': 0.0} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'reg_alpha': 0.0} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'reg_alpha': 0.0} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'reg_alpha': 0.0} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'reg_alpha': 0.0} loss:0.222005
{'reg_alpha': 0.1} train loss: 0.215805, valid loss:0.222623, loss_diff:0.006818
{'reg_alpha': 0.1} train loss: 0.216183, valid loss:0.221403, loss_diff:0.005220
{'reg_alpha': 0.1} train loss: 0.216018, valid loss:0.222417, loss_diff:0.006398
{'reg_alpha': 0.1} train loss: 0.216569, valid loss:0.221808, loss_diff:0.005239
{'reg_alpha': 0.1} train loss: 0.216045, valid loss:0.221995, loss_diff:0.005950
=================>{'reg_alpha': 0.1} loss:0.222049
{'reg_alpha': 0.2} train loss: 0.215623, valid loss:0.222629, loss_diff:0.007007
{'reg_a

param  val_loss_mean  val_loss_std
0   {'reg_alpha': 0.0}       0.222005      0.000468
1   {'reg_alpha': 0.1}       0.222049      0.000434
2   {'reg_alpha': 0.2}       0.222108      0.000413
3   {'reg_alpha': 0.3}       0.222093      0.000400
4   {'reg_alpha': 0.4}       0.222121      0.000437
5   {'reg_alpha': 0.5}       0.222047      0.000589
6   {'reg_alpha': 0.6}       0.222117      0.000492
7   {'reg_alpha': 0.7}       0.222099      0.000565
8   {'reg_alpha': 0.8}       0.222017      0.000491
9   {'reg_alpha': 0.9}       0.222105      0.000540
10  {'reg_alpha': 1.0}       0.222140      0.000471

In [16]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'reg_lambda':[i/10.0 for i in range(0,11,1)]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'reg_lambda': 0.0} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'reg_lambda': 0.0} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'reg_lambda': 0.0} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'reg_lambda': 0.0} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'reg_lambda': 0.0} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'reg_lambda': 0.0} loss:0.222005
{'reg_lambda': 0.1} train loss: 0.216060, valid loss:0.222695, loss_diff:0.006634
{'reg_lambda': 0.1} train loss: 0.216194, valid loss:0.221390, loss_diff:0.005195
{'reg_lambda': 0.1} train loss: 0.216187, valid loss:0.222522, loss_diff:0.006335
{'reg_lambda': 0.1} train loss: 0.216521, valid loss:0.221791, loss_diff:0.005271
{'reg_lambda': 0.1} train loss: 0.216255, valid loss:0.222064, loss_diff:0.005809
=================>{'reg_lambda': 0.1} loss:0.222092
{'reg_lambda': 0.2} train loss: 0.215882, valid loss:0.222628, loss_diff:0.0

param  val_loss_mean  val_loss_std
0   {'reg_lambda': 0.0}       0.222005      0.000468
1   {'reg_lambda': 0.1}       0.222092      0.000476
2   {'reg_lambda': 0.2}       0.222092      0.000436
3   {'reg_lambda': 0.3}       0.222017      0.000476
4   {'reg_lambda': 0.4}       0.222118      0.000342
5   {'reg_lambda': 0.5}       0.222125      0.000446
6   {'reg_lambda': 0.6}       0.222013      0.000473
7   {'reg_lambda': 0.7}       0.222109      0.000473
8   {'reg_lambda': 0.8}       0.222056      0.000412
9   {'reg_lambda': 0.9}       0.222080      0.000413
10  {'reg_lambda': 1.0}       0.222035      0.000433

In [17]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'reg_alpha': [0., .05],
    'reg_lambda':[0., .05]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'reg_alpha': 0.0, 'reg_lambda': 0.0} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'reg_alpha': 0.0, 'reg_lambda': 0.0} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'reg_alpha': 0.0, 'reg_lambda': 0.0} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'reg_alpha': 0.0, 'reg_lambda': 0.0} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'reg_alpha': 0.0, 'reg_lambda': 0.0} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'reg_alpha': 0.0, 'reg_lambda': 0.0} loss:0.222005
{'reg_alpha': 0.0, 'reg_lambda': 0.05} train loss: 0.215974, valid loss:0.222709, loss_diff:0.006735
{'reg_alpha': 0.0, 'reg_lambda': 0.05} train loss: 0.216038, valid loss:0.221485, loss_diff:0.005448
{'reg_alpha': 0.0, 'reg_lambda': 0.05} train loss: 0.216119, valid loss:0.222458, loss_diff:0.006338
{'reg_alpha': 0.0, 'reg_lambda': 0.05} train loss: 0.216095, valid loss:0.221461, loss_diff:0.005367
{'reg_alpha': 0.0, 'reg_la

param  val_loss_mean  val_loss_std
0    {'reg_alpha': 0.0, 'reg_lambda': 0.0}       0.222005      0.000468
1   {'reg_alpha': 0.0, 'reg_lambda': 0.05}       0.222047      0.000504
2   {'reg_alpha': 0.05, 'reg_lambda': 0.0}       0.222157      0.000450
3  {'reg_alpha': 0.05, 'reg_lambda': 0.05}       0.222090      0.000420

In [18]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':8, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'max_depth': [8, 10, 15, 18]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'max_depth': 8} train loss: 0.215871, valid loss:0.222551, loss_diff:0.006680
{'max_depth': 8} train loss: 0.216085, valid loss:0.221391, loss_diff:0.005306
{'max_depth': 8} train loss: 0.215925, valid loss:0.222422, loss_diff:0.006497
{'max_depth': 8} train loss: 0.216365, valid loss:0.221527, loss_diff:0.005163
{'max_depth': 8} train loss: 0.216189, valid loss:0.222131, loss_diff:0.005942
=================>{'max_depth': 8} loss:0.222005
{'max_depth': 10} train loss: 0.215346, valid loss:0.222288, loss_diff:0.006942
{'max_depth': 10} train loss: 0.215494, valid loss:0.221248, loss_diff:0.005754
{'max_depth': 10} train loss: 0.215434, valid loss:0.222286, loss_diff:0.006853
{'max_depth': 10} train loss: 0.215442, valid loss:0.221433, loss_diff:0.005990
{'max_depth': 10} train loss: 0.215330, valid loss:0.221716, loss_diff:0.006387
=================>{'max_depth': 10} loss:0.221794
{'max_depth': 15} train loss: 0.214630, valid loss:0.222029, loss_diff:0.007399
{'max_depth': 15} train lo

param  val_loss_mean  val_loss_std
0   {'max_depth': 8}       0.222005      0.000468
1  {'max_depth': 10}       0.221794      0.000429
2  {'max_depth': 15}       0.221450      0.000396
3  {'max_depth': 18}       0.221356      0.000457

In [19]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':31, 
    'max_depth':18, 
    'learning_rate':0.3, 
    'n_estimators':100, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}

try_params = {
    'num_leaves': [32, 48, 64, 128, 256]
}

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=fit_param, seed=SEED)

{'num_leaves': 32} train loss: 0.214193, valid loss:0.222013, loss_diff:0.007820
{'num_leaves': 32} train loss: 0.214513, valid loss:0.220503, loss_diff:0.005990
{'num_leaves': 32} train loss: 0.214240, valid loss:0.221530, loss_diff:0.007290
{'num_leaves': 32} train loss: 0.214466, valid loss:0.220842, loss_diff:0.006375
{'num_leaves': 32} train loss: 0.214366, valid loss:0.221435, loss_diff:0.007069
=================>{'num_leaves': 32} loss:0.221265
{'num_leaves': 48} train loss: 0.210871, valid loss:0.221536, loss_diff:0.010665
{'num_leaves': 48} train loss: 0.211536, valid loss:0.220142, loss_diff:0.008606
{'num_leaves': 48} train loss: 0.211463, valid loss:0.221319, loss_diff:0.009856
{'num_leaves': 48} train loss: 0.211400, valid loss:0.220481, loss_diff:0.009081
{'num_leaves': 48} train loss: 0.211229, valid loss:0.220944, loss_diff:0.009715
=================>{'num_leaves': 48} loss:0.220885
{'num_leaves': 64} train loss: 0.208893, valid loss:0.221343, loss_diff:0.012450
{'num_l

param  val_loss_mean  val_loss_std
0   {'num_leaves': 32}       0.221265      0.000533
1   {'num_leaves': 48}       0.220885      0.000516
2   {'num_leaves': 64}       0.220781      0.000413
3  {'num_leaves': 128}       0.220823      0.000516
4  {'num_leaves': 256}       0.221391      0.000459

In [20]:
default_params = {
    'boosting_type':'gbdt', 
    'num_leaves':64, 
    'max_depth':18, 
    'learning_rate':0.02, 
    'n_estimators':20000, 
    'min_split_gain':0.0, 
    'min_child_weight':0.001, 
    'min_child_samples':20, 
    'subsample':1., 
    'subsample_freq':1, 
    'colsample_bytree':.6, 
    'reg_alpha':0.0, 
    'reg_lambda':0.0, 
    'random_state':SEED, 
    'n_jobs': 3
}


'''
default_params = {
    'boosting_type':'gbdt', 
    'objective' : 'regression',
    'metric' : 'rmse',
    'num_leaves' : 48,
    'max_depth': 15,
    'learning_rate' : 0.05,
    'colsample_bytree' : 0.6,
    'verbosity' : -1,
    'n_estimators': 20000,
    'random_state':SEED, 
}
'''
fit_param.update({
    'early_stopping_rounds': 50,
    'verbose': 100,
    'eval_metric': 'rmse'
})

lgb_oof_val_pred, lgb_oof_test_pred, models = get_oof_predictions(train_X, train_y, test_X, ml, 
                                                                  default_params, seed=SEED, fit_params=fit_param, 
                                                                  use_eval_set=True)

Training until validation scores don't improve for 50 rounds.
[100]	train's rmse: 0.226186	valid's rmse: 0.228302
[200]	train's rmse: 0.221284	valid's rmse: 0.225013
[300]	train's rmse: 0.218433	valid's rmse: 0.223555
[400]	train's rmse: 0.216636	valid's rmse: 0.222766
[500]	train's rmse: 0.215245	valid's rmse: 0.222235
[600]	train's rmse: 0.214198	valid's rmse: 0.221888
[700]	train's rmse: 0.213315	valid's rmse: 0.221636
[800]	train's rmse: 0.212522	valid's rmse: 0.221388
[900]	train's rmse: 0.211793	valid's rmse: 0.221178
[1000]	train's rmse: 0.211119	valid's rmse: 0.221018
[1100]	train's rmse: 0.210466	valid's rmse: 0.220863
[1200]	train's rmse: 0.209909	valid's rmse: 0.220733
[1300]	train's rmse: 0.209335	valid's rmse: 0.220622
[1400]	train's rmse: 0.208819	valid's rmse: 0.220519
[1500]	train's rmse: 0.208334	valid's rmse: 0.220424
[1600]	train's rmse: 0.207839	valid's rmse: 0.220329
[1700]	train's rmse: 0.207367	valid's rmse: 0.220252
[1800]	train's rmse: 0.206918	valid's rmse: 0.

KeyboardInterrupt: 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
for model in models:
    fig, ax = plt.subplots(figsize=(10, 14))
    lgb.plot_importance(model, max_num_features=100, ax=ax)
    plt.title("Light GBM Feature Importance")
    plt.show()

In [ ]:
pd.DataFrame(data=lgb_oof_val_pred, columns=['all_mean_enc_user_ft_lgb_pred']).to_csv('all_mean_enc_user_ft_oof_val_pred.csv', index=False)
pd.DataFrame(data=lgb_oof_test_pred, columns=['all_mean_enc_user_ft_lgb_pred']).to_csv('all_mean_enc_user_ft_oof_test_pred.csv', index=False)

In [ ]:
test_df = pd.read_csv("test.csv", usecols=['item_id'])
test_pred = pd.read_csv("all_mean_enc_user_ft_oof_test_pred.csv")
test_pred = test_pred.loc[:, 'all_mean_enc_user_ft_lgb_pred'].values
pd.DataFrame(np.clip(test_pred,0,1), 
             index=test_df.item_id,
             columns=['deal_probability']).to_csv('all_mean_enc_user_ft_lgb_submission.csv')

## Ridge

In [ ]:
ml = model_loader(model_type='rg')

In [ ]:
default_params = {
    'alpha': 1.0, 
    'fit_intercept': True, 
    'normalize': False, 
    'copy_X': True, 
    'max_iter': None, 
    'tol': 0.001, 
    'solver':'auto', 
    'random_state': SEED
}

try_params = \
[
    {
        'alpha': [0.01, 0.1, 0.5, 1., 2.],
    }
]

fit_params(train_X, train_y, ml, default_params, try_params, fit_params=None, seed=SEED)

In [ ]:
default_params = {
    'alpha': 1.0, 
    'fit_intercept': True, 
    'normalize': False, 
    'copy_X': True, 
    'max_iter': None, 
    'tol': 0.001, 
    'solver':'auto', 
    'random_state': SEED
}

fit_params = None

rg_oof_val_pred, rg_oof_test_pred, models = get_oof_predictions(train_X, train_y, test_X, ml, 
                                                                  default_params, seed=SEED, fit_params=fit_params, 
                                                                  use_eval_set=False)

In [ ]:
pd.DataFrame(data=rg_oof_val_pred, columns=['text_rg_pred']).to_csv('text_rg_oof_val_pred.csv', index=False)
pd.DataFrame(data=rg_oof_test_pred, columns=['text_rg_pred']).to_csv('text_rg_oof_test_pred.csv', index=False)